*** Variable ***
${new_user_signup_text}     xpath = //*[contains(text(),'New User Signup!')]
${signup_name}   xpath = //input [@name = 'name']
${signup_email}   xpath = //input [@data-qa = 'signup-email']
${signup_btn}      xpath = //button[@data-qa = 'signup-button']
${enter_account_information_text}    xpath = //*[contains(text(),'Enter Account Information')]
${password}     xpath = //input[@id = 'password']
${days}         xpath = //select[@id = 'days']       
${months}       xpath = //select[@id = 'months'] 
${years}        xpath = //select[@id = 'years']    
${news_letter_checkbox}     xpath = //input[@id = 'newsletter']
${special_offer_checkbox}     xpath = //input[@id = 'optin']
${first_name}    xpath = //input[@id = 'first_name']
${last_name}     xpath = //input[@id = 'last_name']
${company}     xpath = //input[@id = 'company']
${address1}     xpath = //input[@id = 'address1']
${address2}     xpath = //input[@id = 'address2']
${country}     xpath = //select[@id = 'country']
${state}      xpath = //input[@id = 'state'] 
${city}      xpath = //input[@id = 'city'] 
${zipcode}      xpath = //input[@id = 'zipcode'] 
${mobile_number}      xpath = //input[@id = 'mobile_number'] 
${create_account_button}   xpath = //button[@data-qa = 'create-account']
${account_created_text}    xpath = //*[contains(text(),'Account Created!')]
${continue_button}   xpath = //a[@data-qa = 'continue-button']
${logged_with_username_text}    xpath = //*[contains(text(),'Logged in as')]
${delete_account_link}          xpath = //a[@href = '/delete_account']
